// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bookdhzfvamkvlborkkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvb2tkaHpmdmFta3ZsYm9ya2tiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2ODY0MjEsImV4cCI6MjA2MDI2MjQyMX0.W9UAw2CrJ4agIMYCT5We5A8Z3CQqRk5QyXjH9aG8RBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});